- name: Apache installation (CentOS)
  tags: httpd,apache,centos
  yum:
    update_cache: yes
    state: latest
  when: ansible_distribution == "CentOS"

- name: start httpd (CentOS)
  tags: httpd,apache,centos
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS"

- name: start httpd (CentOS)
  tags: httpd,apache,centos
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
