
---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    yum:
      update_cache: yes
    when: ansible_distribution == "CentOS"


  - name: install apache2 package
    yum:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS"

  - name: installing nmap
    yum:
      name: nmap
      state: latest
    when: ansible_distribution == "CentOS"
