
---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    tags: centos
    yum:
      update_cache: yes
    when: ansible_distribution == "CentOS"


  - name: install apache2 package
    yum:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS"


  - name: start http(CentOS)
    tags: apache,httpd,centos
    service:
      name: httpd
      state: started
    when: ansible_distribution == "CentOS"


  - name: installing nmap
    tags: centos,nmap   
    yum:
      name: nmap
      state: latest
    when: ansible_distribution == "CentOS"
