- name: Apache installation (Ubuntu)
  tags: apache,ubuntu
  apt:
    name: apache2
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: start Apache (Ubuntu)
  tags: apache,ubuntu
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS"

- name: copy Apache index file (Ubuntu)
  tags: apache,ubuntu
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

