- name: update repository index
  tags: centos
  yum:
    update_cache: yes
  when: ansible_distribution == "CentOS"

- name: update repository index
  tags: ubuntu
  apt:
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

